service: Authorizer

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  test:
    handler: src/handlers/handler.test
    events:
      - http:
          path: api/test
          method: get
          integration: lambda
          cors: true
  auth:
    handler: src/utils/auth.authorize
  chatbot:
    handler: src/handlers/handler.chatbot
    events:
      - http:
          path: api/chatbot
          method: post
          authorizer: auth
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
package:
  exclude:
    - node_modules/**
    - venv
    - __pycache__
