org: arunopt
app: csc-ml
service: csc-ml

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:us-east-1:*:*"
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-wsgi
  - serverless-python-requirements
functions:
  connectionManager:
    handler: src/handlers/handler.connection_manager
    events:
      - websocket:
          route: $connect
          cors: true
      - websocket:
          route: $disconnect
          cors: true
  defaultMessage:
    handler: src/handlers/handler.default_message
    events:
      - websocket:
          route: $default
          cors: true
  sendMessage:
    handler: src/handlers/handler.send_message
    events:
      - websocket:
          route: chatBot
          cors: true
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          method: post
          path: /api/chatbot
          cors: true
package:
  individually: true
  exclude:
    - node_modules/**
    - model/**
    - .vscode/**
  patterns:
    - "!node_modules/**"
    - "!venv/**"
    - "!tmp/**"
    - "!.git/**"

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    slim: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
      - tensorboard
    # dockerizePip: true
    # noDeploy: []
  wsgi:
    app: src/routes/app.app
